# Generated by Django 2.1.3 on 2018-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to='images/%Y/%m/%d'),
        ),
    ]
